server:
  contextPath: /shinyproxy
  useForwardHeader: true
  servlet:
    context-path: /shinyproxy

proxy:
  title: CEU Business Analytics Shiny Proxy
  logo-url: https://www.ceu.edu/sites/default/files/media/user-5/ceulogo_0_1.jpg
  landing-page: /
  heartbeat-rate: 10000
  heartbeat-timeout: 60000
  port: 8080
  docker:
    cert-path: /home/none
    url: http://localhost:2375
    port-range-start: 20000
  specs:
  - id: 01_hello
    display-name: Hello Application
    description: Application which demonstrates the basics of a Shiny app
    container-cmd: ["R", "-e", "shinyproxy::run_01_hello()"]
    container-image: openanalytics/shinyproxy-demo
  - id: bikes
    display-name: Bikes Sales
    description: foobar
    container-image: bikes
logging:
  file:
    shinyproxy.log
